apiVersion: apps/v1
kind: Deployment

metadata:
  name: netflix-deployment
  namespace: netflix
  labels:
    app: netflix

spec:
  replicas: 5

  selector:
    matchLabels:
      app: netflix

  template:
    metadata:
      labels:
        app: netflix

    spec:
      containers:
      - name: netflix
        image: srinu0930/netflixproject:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080