apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix
  namespace: default

spec:
  project: default

  source:
    repoURL: https://github.com/srinucloud/java-project-maven
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: netflix

  syncPolicy:
    automated:
      prune: true
      selfHeal: true